spring.application.name=insight-service
server.port=8085


usage.service.url = http://localhost:8083/api/v1/usage

# OpenAI Groq
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.chat.model=llama-3.1-8b-instant